
let exampleValues = {
  /////////////
  //REQUEST//
  ///////////
  input: {
    "source": "_____String",
    "anonymized": false,
    "chineseSurnameLatin": "_____String",
    "chineseGivenNameLatin": "_____String",
    "id": "e630dda5-13b3-42c5-8f1d-648aa8a21c42",
    "firstName": "Jim",
    "lastName": "Smith",
    "gender": "male",
    "knownGender": "female",
    "chineseName": "_____String",
    "name": "Jim Smith",
    "countryIso2From": "US",
    "firstNameFrom": "Jim",
    "lastNameFrom": "Smith",
    "countryIso2To": "US",
    "firstNameTo": "Audrey",
    "lastNameTo": "Carrera",
    "countryIso2": "US",
    "personalNameFull": "_____String",
    "fullName": "Jim Smith",
    "japaneseName": "_____String",
    "japaneseSurname": "_____String",
    "japaneseGivenName": "_____String",
    "japaneseSurnameLatin": "Nagasawa",
    "japaneseGivenNameLatin": "Masami",
    "japaneseSurnameKanji": "_____String",
    "japaneseGivenNameKanji": "_____String",
    "learnable": true,
    "properNoun": "_____String",
    "nameFull": "_____String",
    "phoneNumber": "0011223344",
    "script": "LATIN",
    "countryOrigin": "_____string",
    "countryOriginAlt": "_____string",
    "countriesOriginTop": "_____array",
    "score": "_____number",
    "regionOrigin": "_____string",
    "topRegionOrigin": "Americas",
    "subRegionOrigin": "Northern America",
    "probabilityCalibrated": 0.323315383020918,
    "probabilityAltCalibrated": 0.3475781739924387,
    "countryIso2Alt": "NZ",
    "phoneNumberE164": "+10011223344",
    "classifierName": "_____String",
    "zip5Code": "_____String",
    "zipCode": "_____string"
  },
  ////////////
  //RESPONSE//
  //////////
  output: {
    "softwareNameAndVersion": "_____string",
    "softwareVersion": "_____array",
    "classifiers": "_____array",
    "apiKey": "77afd518a85798fa3723f5ec8120adb7",
    "planStarted": "_____integer",
    "priorPlanStarted": "_____integer",
    "planEnded": "_____integer",
    "taxRate": "_____number",
    "planName": "_____string",
    "planBaseFeesKey": "_____string",
    "planStatus": "_____string",
    "planQuota": "_____integer",
    "priceUSD": "_____number",
    "priceOverageUSD": "_____number",
    "price": "_____number",
    "priceOverage": "_____number",
    "currency": "_____string",
    "currencyFactor": "_____number",
    "stripeCustomerId": "_____string",
    "stripeStatus": "_____string",
    "stripeSubscription": "_____string",
    "userId": "_____string",
    "subscriptionStarted": "_____integer",
    "periodStarted": "_____integer",
    "periodEnded": "_____integer",
    "stripeCurrentPeriodEnd": "_____integer",
    "stripeCurrentPeriodStart": "_____integer",
    "billingStatus": "_____string",
    "usage": "_____integer",
    "softLimit": "_____integer",
    "hardLimit": "_____integer",
    "overageExclTax": "_____number",
    "overageInclTax": "_____number",
    "overageCurrency": "_____string",
    "overageQuantity": "_____integer",
    "admin": true,
    "vetted": true,
    "learnable": true,
    "anonymized": true,
    "partner": true,
    "striped": true,
    "corporate": true,
    "disabled": true,
    "apiService": "_____string",
    "createdDateTime": "_____integer",
    "totalUsage": "_____integer",
    "lastFlushedDateTime": "_____integer",
    "lastUsedDateTime": "_____integer",
    "serviceFeaturesUsage": "object",
    "serviceName": "_____string",
    "serviceGroup": "_____string",
    "costInUnits": "_____integer",
    "script": "LATIN",
    "id": "e630dda5-13b3-42c5-8f1d-648aa8a21c42",
    "firstName": "_____string",
    "lastName": "_____string",
    "orderOption": "_____string",
    "matchCandidates": "_____array",
    "latinName": "_____string",
    "originalName": "_____string",
    "sourceLanguage": "_____string",
    "targetLanguage": "_____string",
    "sourceScript": "_____string",
    "targetScript": "_____string",
    "score": 6.302182927650384,
    "matchStatus": "_____string",
    "likelyGender": "_____string",
    "genderScale": "_____number",
    "probabilityCalibrated": 0.323315383020918,
    "countryOrigin": "_____string",
    "countryOriginAlt": "_____string",
    "countriesOriginTop": "_____array",
    "regionOrigin": "_____string",
    "topRegionOrigin": "_____string",
    "subRegionOrigin": "_____string",
    "probabilityAltCalibrated": 0.3475781739924387,
    "ethnicityAlt": "_____string",
    "ethnicity": "_____string",
    "lifted": true,
    "countryIso2": "_____string",
    "ethnicitiesTop": "_____array",
    "name": "_____string",
    "country": "US",
    "countryAlt": "NZ",
    "region": "Northern America",
    "topRegion": "Americas",
    "subRegion": "Northern America",
    "countriesTop": [
      "US",
      "NZ",
      "CA",
      "GB",
      "AU",
      "IE",
      "JM",
      "BM",
      "BS",
      "LR"
    ],
    "feedbackCredits": "_____integer",
    "commonType": "_____string",
    "commonTypeAlt": "_____string",
    "nameParserType": "LN1FN1",
    "nameParserTypeAlt": null,
    "internationalPhoneNumberVerified": "_____string",
    "phoneCountryIso2Verified": "_____string",
    "phoneCountryCode": "_____integer",
    "phoneCountryCodeAlt": "_____integer",
    "phoneCountryIso2": "_____string",
    "phoneCountryIso2Alt": "_____string",
    "originCountryIso2": "_____string",
    "originCountryIso2Alt": "_____string",
    "phoneNumber": "_____string",
    "verified": true,
    "classifierName": "_____string",
    "taxonomyClasses": "_____array",
    "raceEthnicityAlt": "_____string",
    "raceEthnicity": "_____string",
    "raceEthnicitiesTop": "_____array"
  }
};

module.exports = exampleValues;